{{- if .Values.dataVolume.enabled }}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ template "local-ai.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "local-ai.labels" . | nindent 4 }}
spec:
  contentType: archive
  source:
    {{ .Values.dataVolume.source.type }}:
      url: {{ .Values.dataVolume.source.url }}
      secretRef: {{ template "local-ai.fullname" . }}
      {{- if and (eq .Values.dataVolume.source.type "http") .Values.dataVolume.source.secretExtraHeaders }}
      secretExtraHeaders: {{ .Values.dataVolume.source.secretExtraHeaders }}
      {{- end }}
      {{- if .Values.dataVolume.source.caCertConfigMap }}
      caCertConfigMap: {{ .Values.dataVolume.source.caCertConfigMap }}
      {{- end }}
  pvc:
    accessModes: {{ .Values.dataVolume.pvc.accessModes }}
    resources:
      requests:
        storage: {{ .Values.dataVolume.pvc.size }}
---
{{- if .Values.dataVolume.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "local-ai.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "local-ai.labels" . | nindent 4 }}
data:
  accessKeyId: {{ .Values.dataVolume.secret.username }}
  secretKey: {{ .Values.dataVolume.secret.password }}
{{- end }}
{{- end }}