description: |
  A text-to-image model that uses Stable Diffusion 1.5 to generate images from text prompts. This model is DreamShaper model by Lykon.
icon: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/dd9b038c-bd15-43ab-86ab-66e145ad7ff2/width=450/26072158-132340247-8k%20portrait%20of%20beautiful%20cyborg%20with%20brown%20hair,%20intricate,%20elegant,%20highly%20detailed,%20majestic,%20digital%20photography,%20art%20by%20artg_ed.jpeg
license: other
urls:
- https://civitai.com/models/4384/dreamshaper
name: dreamshaper
config_file: |
  backend: diffusers
  step: 25
  f16: true

  diffusers:
    pipeline_type: StableDiffusionPipeline
    cuda: true
    enable_parameters: "negative_prompt,num_inference_steps"
    scheduler_type: "k_dpmpp_2m"
files:
- filename: DreamShaper_8_pruned.safetensors
  sha256: 879db523c30d3b9017143d56705015e15a2cb5628762c11d086fed9538abd7fd
  uri: huggingface://Lykon/DreamShaper/DreamShaper_8_pruned.safetensors
prompt_templates: []
