description: |
  Parler-TTS is a lightweight text-to-speech (TTS) model that can generate high-quality, natural sounding speech in the style of a given speaker (gender, pitch, speaking style, etc). It is a reproduction of work from the paper Natural language guidance of high-fidelity text-to-speech with synthetic annotations by Dan Lyth and Simon King, from Stability AI and Edinburgh University respectively.
icon: ""
license: apache-2.0
urls:
- https://github.com/huggingface/parler-tts
name: ""
config_file: |
  backend: parler-tts
files: []
prompt_templates: []
